name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
          workspace: ${{ env.TF_WORKSPACE }}

      - run: terraform init

      - id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true

      - name: Show Plan Output
        if: always()
        run: cat tfplan

      - name: Output Plan Results
        if: always()
        run: |
          echo "Plan exit code: ${{ steps.plan.outcome }}"
          echo "Plan output:"
          terraform show -no-color tfplan
