name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Upload configuration to Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        with:
          workspace: learn-terraform-github-actions
          directory: ./
          speculative: true
        env:
          TF_CLOUD_ORGANIZATION: aws_wordpress_github
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          TF_WORKSPACE: learn-terraform-github-actions
          CONFIG_DIRECTORY: ./

      - run: terraform init

      - id: plan
        run: terraform plan -no-color -out=tfplan
        continue-on-error: true

      - name: Show Plan Output
        if: always()
        run: cat tfplan

      - name: Output Plan Results
        if: always()
        run: |
          echo "Plan exit code: ${{ steps.plan.outcome }}"
          echo "Plan output:"
          terraform show -no-color tfplan
